categories_and_channels:
  type: list
  default: ""
  description:
    en: "List of the secure categories and chat channels to hide the lock badge icon for. 
    Must be in semi-colon delimited format with category-slug;category-ID. Channel slug name must be same as respective category slug name. Separate parent categories and subcategories with a dash and use subcategory ID.<br>
    (For example: staff;3 or off-topic;5)"

Show all lock icons for admins:
  type: bool
  default: "true"
  description:
    en: "Disable this if you want the lock badge icon to be hidden for admins as well as regular users."
